import MemoryTag from 'solanum-core/server/MemoryTag.js'
import OpcUaTag from 'solanum-opcua/server/OpcUaTag.js'
import ST_Motor from '../server/tagTypes/ST_Motor.js'

let tags = {
    testMemoryTag: new MemoryTag({
        defaultValue: 0,
    }),
    Motors: {
        M0   : new ST_Motor({sId:    'M0'}),
        M1   : new ST_Motor({sId:    'M1'}),
        M2   : new ST_Motor({sId:    'M2'}),
        M3   : new ST_Motor({sId:    'M3'}),
        M4   : new ST_Motor({sId:    'M4'}),
        M5   : new ST_Motor({sId:    'M5'}),
        M6   : new ST_Motor({sId:    'M6'}),
        M7   : new ST_Motor({sId:    'M7'}),
        M8   : new ST_Motor({sId:    'M8'}),
        M9   : new ST_Motor({sId:    'M9'}),
        M10  : new ST_Motor({sId:   'M10'}),
        M11  : new ST_Motor({sId:   'M11'}),
        M12  : new ST_Motor({sId:   'M12'}),
        M13  : new ST_Motor({sId:   'M13'}),
        M14  : new ST_Motor({sId:   'M14'}),
        M15  : new ST_Motor({sId:   'M15'}),
        M16  : new ST_Motor({sId:   'M16'}),
        M17  : new ST_Motor({sId:   'M17'}),
        M18  : new ST_Motor({sId:   'M18'}),
        M19  : new ST_Motor({sId:   'M19'}),
        M20  : new ST_Motor({sId:   'M20'}),
        M21  : new ST_Motor({sId:   'M21'}),
        M22  : new ST_Motor({sId:   'M22'}),
        M23  : new ST_Motor({sId:   'M23'}),
        M24  : new ST_Motor({sId:   'M24'}),
        M25  : new ST_Motor({sId:   'M25'}),
        M26  : new ST_Motor({sId:   'M26'}),
        M27  : new ST_Motor({sId:   'M27'}),
        M28  : new ST_Motor({sId:   'M28'}),
        M29  : new ST_Motor({sId:   'M29'}),
        M30  : new ST_Motor({sId:   'M40'}),
        M31  : new ST_Motor({sId:   'M41'}),
        M32  : new ST_Motor({sId:   'M42'}),
        M33  : new ST_Motor({sId:   'M43'}),
        M34  : new ST_Motor({sId:   'M44'}),
        M35  : new ST_Motor({sId:   'M45'}),
        M36  : new ST_Motor({sId:   'M46'}),
        M37  : new ST_Motor({sId:   'M47'}),
        M38  : new ST_Motor({sId:   'M48'}),
        M39  : new ST_Motor({sId:   'M49'}),
        M40  : new ST_Motor({sId:   'M40'}),
        M41  : new ST_Motor({sId:   'M41'}),
        M42  : new ST_Motor({sId:   'M42'}),
        M43  : new ST_Motor({sId:   'M43'}),
        M44  : new ST_Motor({sId:   'M44'}),
        M45  : new ST_Motor({sId:   'M45'}),
        M46  : new ST_Motor({sId:   'M46'}),
        M47  : new ST_Motor({sId:   'M47'}),
        M48  : new ST_Motor({sId:   'M48'}),
        M49  : new ST_Motor({sId:   'M49'}),
        M50  : new ST_Motor({sId:   'M50'}),
        M51  : new ST_Motor({sId:   'M51'}),
        M52  : new ST_Motor({sId:   'M52'}),
        M53  : new ST_Motor({sId:   'M53'}),
        M54  : new ST_Motor({sId:   'M54'}),
        M55  : new ST_Motor({sId:   'M55'}),
        M56  : new ST_Motor({sId:   'M56'}),
        M57  : new ST_Motor({sId:   'M57'}),
        M58  : new ST_Motor({sId:   'M58'}),
        M59  : new ST_Motor({sId:   'M59'}),
        M60  : new ST_Motor({sId:   'M60'}),
        M61  : new ST_Motor({sId:   'M61'}),
        M62  : new ST_Motor({sId:   'M62'}),
        M63  : new ST_Motor({sId:   'M63'}),
        M64  : new ST_Motor({sId:   'M64'}),
        M65  : new ST_Motor({sId:   'M65'}),
        M66  : new ST_Motor({sId:   'M66'}),
        M67  : new ST_Motor({sId:   'M67'}),
        M68  : new ST_Motor({sId:   'M68'}),
        M69  : new ST_Motor({sId:   'M69'}),
        M70  : new ST_Motor({sId:   'M70'}),
        M71  : new ST_Motor({sId:   'M71'}),
        M72  : new ST_Motor({sId:   'M72'}),
        M73  : new ST_Motor({sId:   'M73'}),
        M74  : new ST_Motor({sId:   'M74'}),
        M75  : new ST_Motor({sId:   'M75'}),
        M76  : new ST_Motor({sId:   'M76'}),
        M77  : new ST_Motor({sId:   'M77'}),
        M78  : new ST_Motor({sId:   'M78'}),
        M79  : new ST_Motor({sId:   'M79'}),
        M80  : new ST_Motor({sId:   'M80'}),
        M81  : new ST_Motor({sId:   'M81'}),
        M82  : new ST_Motor({sId:   'M82'}),
        M83  : new ST_Motor({sId:   'M83'}),
        M84  : new ST_Motor({sId:   'M84'}),
        M85  : new ST_Motor({sId:   'M85'}),
        M86  : new ST_Motor({sId:   'M86'}),
        M87  : new ST_Motor({sId:   'M87'}),
        M88  : new ST_Motor({sId:   'M88'}),
        M89  : new ST_Motor({sId:   'M89'}),
        M90  : new ST_Motor({sId:   'M90'}),
        M91  : new ST_Motor({sId:   'M91'}),
        M92  : new ST_Motor({sId:   'M92'}),
        M93  : new ST_Motor({sId:   'M93'}),
        M94  : new ST_Motor({sId:   'M94'}),
        M95  : new ST_Motor({sId:   'M95'}),
        M96  : new ST_Motor({sId:   'M96'}),
        M97  : new ST_Motor({sId:   'M97'}),
        M98  : new ST_Motor({sId:   'M98'}),
        M99  : new ST_Motor({sId:   'M99'}),
    }
}

for (let i = 100; i < 3000; i++) {
    tags[`Motors.M${i}`] = new ST_Motor({sId: `M${i}`})
}
tags.watchDog = new OpcUaTag({
    connection: "DemoServer",
    subscription: "default",
    ns: 1,
    nodeId: "ns=1;s=iWatchDog",
})
    /*
    testUdtInst: {
            type: "UdtInstance",
            udtType: "ST_MOTOR",
            params: {
                    OPCUA: "PLC01",
                    motorId: "dol_A001",
                    ns: 4,
                }
    },*/



export default tags
